### ISSUE TITLE
Chatty-Bot epic

### ISSUE THREAD

**Issue by varmoh** [varmoh/Chatty-Bot#1]
#### Here the Chatty-Bot epic will be written.
Chatty-Bot is a python based simple chatbot. 
All the modules that this project will need, will be incoroprated into a special
 `install_modules.py` script. 

Featured will be:
##### Front-end
 - Simple chat window, for enduser-to-bot interaction varmoh/Chatty-Bot#2 
 - Simple training/admin panel to teach the "Chatty-Bot" varmoh/Chatty-Bot#2 
 
##### Back-end
 - Bot engine varmoh/Chatty-Bot#3 
 - Endpoint scripts for connecting front-end with back-end

#### Project epic AC's
- [ ] Project has 3 language versions and frontend will act according to language choise. Also, taught triggers/answers should be stored in languagebased databases/tables
- [ ] Back-end componends are running
- [ ] Front-end components are running
- [ ] Training works
- [ ] User-to-bot interaction is working
- [ ] Chatty-Bot will be published in Amazon AWS
